# Generated by Django 5.0.14 on 2026-04-16 00:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference',
            field=models.CharField(blank=True, help_text='Bank ref / transaction ID', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='agreed_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Agreed Price (ZAR)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Amount Paid (ZAR)'),
        ),
        migrations.AlterField(
            model_name='project',
            name='delivery_url',
            field=models.URLField(blank=True, verbose_name='Live URL / Staging Link'),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='admin_notified',
            field=models.BooleanField(default=False, verbose_name='Admin notified?'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='budget',
            field=models.CharField(blank=True, choices=[('r2500_5000', 'R2,500 – R5,000'), ('r5000_12000', 'R5,000 – R12,000'), ('r12000_25000', 'R12,000 – R25,000'), ('r25000_plus', 'R25,000+')], max_length=20, verbose_name='Budget Range'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='business_name',
            field=models.CharField(blank=True, max_length=120, verbose_name='Business / Company'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='client_notified',
            field=models.BooleanField(default=False, verbose_name='Auto-reply sent?'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Enquiry Date'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='internal_notes',
            field=models.TextField(blank=True, help_text='Private — NOT shown to client'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='message',
            field=models.TextField(verbose_name='Project Details / Message'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone / WhatsApp'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='project_type',
            field=models.CharField(choices=[('landing_page', 'Landing Page'), ('business_site', 'Business Website (5+ pages)'), ('web_app', 'Web App / Portal'), ('ecommerce', 'E-Commerce Store'), ('three_d', '3D / Interactive'), ('cad', 'CAD / Architectural Drawing'), ('other', 'Other')], default='other', max_length=30, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='quoterequest',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('briefed', 'Briefed'), ('in_progress', 'In Progress'), ('revision', 'Revision'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='new', max_length=20, verbose_name='Pipeline Status'),
        ),
    ]
